### ISSUE TITLE
Move Primary repo to https://github.com/chromebrew/chromebrew

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#6133]
**To-do list.** _(Open for discussion)_
- [ ] Set date for changeover. _September 30, 2021?_
- [x] Push changes to new repo during transition period. (Started by @satmandu )
  - [ ] Use main as default branch on new repo?
- [x] Change URLs in `install.sh`
- [x] Update `crew` to modify git repo sync settings to point to new repo
- [x] Sync issues and PRs
- [x] Move Wiki (remove deprecated FAQ sections and clean up)
- [x] Update Readme
- [x] Modify text in packages which refers to the old repo.
- [x] Redirect https://github.com/skycocker/chromebrew to https://github.com/chromebrew/chromebrew (possible?)
- [ ] ~Archive old repo~
- [x] Move [Github pages](https://skycocker.github.io/chromebrew/)
- [ ] **Deprecation for i686, `x86_64 w/ glibc 2.27` (EOL before M92), `armv7l w/ glibc 2.27` (EOL before M92)**
  - This will affect:
  - (Start compiling all software on glibc 2.32 based systems/containers. _Glibc 2.32 was added in M92._)

Suggested deprecated devices (not receiving M92):
big
blaze
buddy
butterfly
clapper
daisy
falco-li
gandof
glimmer
guado
jacuzzi
jaq
jerry
kitty
leon
link
lulu
lumpy
mario
mccloud
mickey
mighty
minnie
monroe
paine
panther
parrot
peppy
pi
pit
puff
quawks
rikku
samus
skate
speedy
spring
squawks
stout
stumpy
terra
tidus
tricky
volteer
wolf
x86-alex-he
x86-zgb-he
yuna
zako
zork

</body>

</html>

**Comment by supechicken** [comment]
The homepage has just moved to https://chromebrew.github.io

**Comment by Zopolis4** [comment]
> The homepage has just moved to https://chromebrew.github.io

To that end, we should probably update the github website.

**Comment by saltedcoffii** [comment]
Alright let's get this done! It's super easy.
@uberhacker, can you:
- delete the https://github.com/chromebrew/chromebrew repository

**Comment by uberhacker** [comment]
It's actually easier than that.  All we need to do is add a remote to git@github.com:skycocker/chromebrew.git and `git pull` everything over.  We just need @skycocker to add a redirect to the new repo immediately afterwards and that should do it.

**Comment by saltedcoffii** [comment]
will that also transfer issues, pull requests, follows, etc.?

**Comment by uberhacker** [comment]
No, that only pulls over the repo code.  I guess we do need to remove the https://github.com/chromebrew/chromebrew repo.

**Comment by uberhacker** [comment]
Regardless, we need @skycocker to initiate the transfer.

**Comment by supechicken** [comment]
> will that also transfer issues, pull requests, follows, etc.?

Yes, it *should*. If I remember correctly, all people who stared the repo are synced and forks are repointed to the new repo when I transfer the `crew-launcher` repo to chromebrew org

**Comment by Zopolis4** [comment]
I dont even know if we need to do that-- I think we can just transfer ownership of the repository from skycocker to chromebrew: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by Zopolis4** [comment]
https://github.com/chromebrew/chromebrew is now live, I'd be happy to transfer the wiki but I don't have the required permissions to create a wiki.

**Comment by skycocker** [comment]
@Zopolis4 looks like I can't manage permissions on the chromebrew/chromebrew repo, so the owner has to grant you that. I remember that last time there was an initiative to transfer the repo, I was worried about whether the existing urls in our scripts will follow redirects from the hardcoded skycocker/chromebrew to chromebrew/chromebrew. Do we know for sure it will not break the local chromebrew setup for everyone?

**Comment by saltedcoffii** [comment]
Yes, direct URLs like wget and curl also follow redirects,

**Comment by skycocker** [comment]
Looks like I need permissions to create repositories in the `chromebrew` organization, which I don't have - once one of you is able to grant me one, I'll be happy to initiate a transfer.

**Comment by satmandu** [comment]
Yes that's fine.

**Comment by skycocker** [comment]
Ok - transfer has been initiated 💁‍♂️ let me know if you need anything more.

**Comment by supechicken** [comment]
@skycocker Could you also change the homepage URL to https://chromebrew.github.io in the description of this repo 😃

**Comment by uberhacker** [comment]
Thank you for the transfer @skycocker.  We will continue to include your name and recognize the hard work you did to start this project.  And as always, we welcome your input and suggestions to make it better.

**Comment by skycocker** [comment]
Updated the description. Thank you all for taking chromebrew so far! 💪

**Comment by saltedcoffii** [comment]
yay! we did it!! Thank you so much.
